config/routes.rb
Rails.application.routes.draw do
  # root to: 'toppages#index'
  root to: 'topics#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'

  #botで収集する機能は廃止
  # get 'receive', to: 'topics#receive'
  # post 'receive', to: 'topics#receive'

  get 'topic_all', to: 'topics#all'
  post 'topic_all/search', to: 'topics#all_process'
  get 'topic_all/search', to: 'topics#all_process'

  # get 'topics/all_post', to: 'topics#all_post'

  get 'topic_user', to: 'topics#user'
  post 'topic_user/search', to: 'topics#user_process'
  get 'topic_user/search', to: 'topics#user_process'

  get 'past_post', to: 'topics#past_post'
  post 'past_post', to: 'topics#past_post'

  get 'topics/follow', to: 'topics#follow'
  post 'topics/follow', to: 'topics#follow'
  get 'topics/unfollow', to: 'topics#unfollow'
  post 'topics/unfollow', to: 'topics#unfollow'

  get 'topics/:id/search', to: 'topics#show_process'
  post 'topics/:id/search', to: 'topics#show_process'

  get 'update_latest', to: 'topics#update_latest'

  #テストコード用
  # get 'keywd', to: 'record#keywd'
  # post 'keywd_process', to: 'record#keywd_process'

  resources :users, only: [:index, :show, :new, :create] do
    # member do
    #   get :followings
    #   get :followers
    #   get :favoritenows # favoritepostsの左部結合部のtypetalks
    #   get :post_users # favoritepostsの左部結合部のtypetalksから参照したusers
    # end
    # 今は検索機能は使用しない
    # collection do
    #   get :searc　
    # end
  end

  # resources :typetalks, only: [:create, :destroy]
  # resources :relationships, only: [:create, :destroy]
  # 投稿のお気に入り機能
  # resources :favoriteposts, only: [:create, :destroy]

  #typetalk用
  resources :topics, only: [:index, :show, :new, :create, :destroy, :all_post]
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :topicId, presence: true
  
  has_many :posts

  def delete_post(post)
    target = self.posts.find_by(id: post.id)
    target.destroy if target
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :require_user_logged_in, only: [
      :index,
      :show,
      :show_process,
      :new,
      :create,
      :destroy,
      :all,
      :all_process,
      :user,
      :user_process,
      :past_post,
      :update_latest
  ]
  before_action :existsTopic, only: [:show]

  # この↓一文がないとCSRFチェックでこけるので、APIをやりとりしているControllerには必要
  skip_before_filter :verify_authenticity_token

  def receive
    # 読み込み時に一度パースが必要
    json_request = JSON.parse(request.body.read)

    # パース後のデータを表示
    # p "json_request => #{json_request}"
    # p "#{json_request.to_hash}"

    # 各要素へのアクセス方法
    # p "glossary => #{json_request["glossary"]}"
    # p "glossary.title => #{json_request["glossary"]["title"]}"

    # この後、postされたデータをDBに突っ込むなり、必要な処理を記述してください。
    if !json_request.blank?
      post = json_request
      @post = Post.new
      topic = Topic.find_or_initialize_by(topicId: post["topic"]["id"].to_s)
      if topic.new_record?
        # 新規作成の場合は保存
        # 新規作成時に行いたい処理を記述
        if topic.save
          p 'トピックを登録しました。'
        else
          p 'トピックの登録に失敗しました。'
        end
      end
      @post.topic = topic
      @post.post_id = post["post"]["id"].to_s
      @post.post_user_name = post["post"]["account"]["name"].to_s
      @post.like = post["post"]["likes"].count
      @post.posted = Time.parse(post['createdAt']).in_time_zone
      if @post.save
        p '投稿を登録しました。'
      else
        p '投稿の登録に失敗しました。'
      end
    else
      post = {'status' => 500}
    end

    render :json => post
  end

  def index
    @user = current_user
    @topics = Array.new
    @imageUrl = Array.new #今は使っていない。この変数がないと、viewがエラーになる。
    #Herokuのデータベースが1万レコードまでしか記録できないので、常に表示する。
    @record_count = Topic.all.count + Post.all.count + User.all.count
    http = setup_http
    access_token = get_access_token(http, "my")
    res = call_api(access_token, http, "/api/v1/topics")

    if res != false
      res['topics'].each do |topic|
        topic_data = Topic.find_or_create_by(topicId: topic["topic"]["id"].to_s)
        #todo:この処理は、elseのみしか分岐していない様子なので、削除する
        if topic_data.updated_at.nil? then
          date = topic_data.created_at.in_time_zone
        else
          date = topic_data.updated_at.in_time_zone
        end
        
        if topic_data.register == "1" then
          from = Post.where(topic: topic_data).minimum(:posted)
          to = Post.where(topic: topic_data).maximum(:posted)
        end
        
        @topics.push({
                         'id' => topic['topic']['id'].to_s,
                         'name' => topic['topic']['name'].to_s,
                         'updated_at' => date,
                         'register' => topic_data.register,
                         'from' => from,
                         'to' => to
                     })
      end
    end
  end

  def show
    topic = Topic.find_by(topicId: params[:id])
    # 初回アクセス時のみ過去200件を取得
    if topic.created_at == topic.updated_at then
      http = setup_http
      access_token = get_access_token(http, "topic.read")
      res = call_api(access_token, http, "/api/v1/topics/#{topic.topicId}?count=200&direction=backward")
      if res != false
        res['posts'].each do |post|
          if Post.where(post_id: post['id']).exists? then
            @post = Post.find_by(post_id: post['id'])
            @post.like = post['likes'].count
          else
            @post = Post.new
            @post.topic = topic
            @post.post_id = post['id'].to_s
            @post.post_user_name = post['account']['name'].to_s
            @post.like = post['likes'].count
            @post.posted = Time.parse(post['createdAt']).in_time_zone
          end
          @post.save
        end
        topic.updated_at = Time.now()
        topic.save
        flash.now[:success] = "「#{res['topic']['name']}」の過去の投稿を取得しました。"
      else
        flash.now[:danger] = 'トピックが見つかりません、管理者に問い合わせてください。'
      end
    end

    @form = TermFindForm.new
    @from = Time.now().beginning_of_month
    @to = Time.now().end_of_month
    getShowList(@from, @to)
  end

  #検索ボタンがクリックされた時の処理
  def show_process
    @form = TermFindForm.new(params[:term_find_form].permit(:post_from, :post_to))
    @from = @form.post_from
    @to = @form.post_to
    getShowList(@from, @to)
    render :show
  end

  #全トピックの集計を表示
  def all
    @form = TermFindForm.new
    @from = Time.now().beginning_of_month
    @to = Time.now().end_of_month
    getAllPost(@from, @to)
  end

  #検索ボタンがクリックされた時の処理
  def all_process
    @form = TermFindForm.new(params[:term_find_form].permit(:post_from, :post_to))
    @from = @form.post_from
    @to = @form.post_to
    getAllPost(@from, @to)
    render :all
  end

  #ユーザー毎のイイね数
  def user
    @form = TermFindForm.new
    @from = Time.now().beginning_of_month
    @to = Time.now().end_of_month
    getUserLikeCount(@from, @to)
  end

  #検索ボタンがクリックされた時の処理
  def user_process
    @form = TermFindForm.new(params[:term_find_form].permit(:post_from, :post_to))
    @from = @form.post_from
    @to = @form.post_to
    getUserLikeCount(@from, @to)
    render :user
  end

  #対象トピックの過去200件のいいね数を取得
  def past_post
    topic = Topic.find_by(topicId: params[:id])
    http = setup_http
    access_token = get_access_token(http, "topic.read")
    res = call_api(access_token, http, "/api/v1/topics/#{topic.topicId}?count=200&direction=backward")
    if res != false
      res['posts'].each do |post|
        if Post.where(post_id: post['id']).exists? then
          @post = Post.find_by(post_id: post['id'])
          @post.like = post['likes'].count
        else
          @post = Post.new
          @post.topic = topic
          @post.post_id = post['id'].to_s
          @post.post_user_name = post['account']['name'].to_s
          @post.like = post['likes'].count
          @post.posted = Time.parse(post['createdAt']).in_time_zone
        end
        @post.save
      end
      topic.updated_at = Time.now()
      topic.save
      flash.now[:success] = "「#{res['topic']['name']}」の過去の投稿を取得しました。"
    else
      flash.now[:danger] = 'トピックが見つかりません、管理者に問い合わせてください。'
    end
  end

  def update_latest
    topics = Topic.all
    http = setup_http
    access_token = get_access_token(http, "topic.read")

    topics.each do |topic|
      posts = Post.where(topic: topic)

      posts.each do |post|
        res_body = call_api(access_token, http, "/api/v1/topics/#{topic.topicId}/posts/#{post.post_id.to_i}")
        if res_body != false
          post.like = res_body['post']['likes'].count
          post.posted = Time.parse(res_body['post']['createdAt']).in_time_zone
          post.save
        else
          # topic.delete_post(post)
          p "#{post.post_id.to_i} is empty"
        end
      end
    end
    flash.now[:success] = 'トピックを最新の状態に更新しました。'
  end

  #トピックを記録対象にする
  def follow
    @topic = Topic.find_by(topicId: params[:id])
    @topic.register = "1"
    @topic.save
  end

  #トピックを記録対象外にする
  def unfollow
    @topic = Topic.find_by(topicId: params[:id])
    @topic.register = "0"
    @topic.save

    # posts = Post.where(topic: @topic)
    # posts.delete_all
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.build(topic_params)
    @topic.topicId = @topic.topicId.split('/').last
    if @topic.save
      flash[:success] = 'トピックを登録しました。'
      redirect_to @topic
    else
      flash.now[:danger] = 'トピックの登録に失敗しました。'
      render :new
    end
  end

  def destroy
  end

  private

  def topic_params
    params.require(:topic).permit(:topicId)
  end

  def existsTopic
    unless Topic.exists?(topicId: params[:id])
      flash[:danger] = 'トピックが見つかりませんでした。'
      redirect_to root_path
    end
  end

  #typetalkのアクセストークンを生成する。
  def get_access_token(http, scope)
    client_id = ENV['CLIENT_ID']
    client_secret = ENV['CLIENT_SECRET']

    # get an access token
    res = http.post(
        '/oauth2/access_token',
        "client_id=#{client_id}&client_secret=#{client_secret}&grant_type=client_credentials&scope=#{scope}"
    )
    if res.code != '200'
      return false
    end
    json = JSON.parse(res.body)
    return json['access_token']
  end

  #httpインスタンスを生成する。
  def setup_http
    http = Net::HTTP.new('typetalk.in', 443)
    http.use_ssl = true
    return http
  end

  #accesstokenとhttpオブジェクトからapiを呼び出す。
  def call_api(access_token, http, url)
    req = Net::HTTP::Get.new(url.to_s)
    req['Authorization'] = "Bearer #{access_token}"
    res = http.request(req)
    if res.code != '200'
      return false
    end
    return JSON.parse(res.body)
  end

  #全ての投稿を取得する。
  def getAllPost(from, to)
    @topic_name = 'すべてのトピックの集計'
    @post_data = Array.new
    http = setup_http
    access_token = get_access_token(http, "topic.read")
    @posts = Post.where(like: 1..Float::INFINITY, posted: from..to).order(like: :desc).page(params[:page]).per(10)
    p @posts

    @posts.each do |post|
      topic = Topic.find(post.topic_id)
      res = call_api(access_token, http, "/api/v1/topics/#{topic.topicId}/posts/#{post.post_id.to_i}")
      if res != false
        created_time = res['post']['createdAt']
        created_time_to_time = Time.parse(created_time).in_time_zone

        post_data = {
            "post_id" => res['post']['id'],
            "topic_id" => res['post']['topicId'],
            "name" => res['post']['account']['fullName'],
            "message" => res['post']['message'],
            "like" => post.like,
            "imageUrl" => res['post']['account']['imageUrl'],
            "created_at" => created_time_to_time.to_s
        }
        @post_data.push(post_data)
      else
        # topic.delete_post(post)
        p "#{post.post_id.to_i} is empty"
      end
    end
  end

  #ユーザーごとのいいね数を取得する。
  def getUserLikeCount(from, to)
    @topic_name = 'ユーザーごとの集計'
    @post_data = Array.new
    page = Array.new
    http = setup_http
    access_token = get_access_token(http, "my")

app/views/topics/_post_list.html.erb
<ul class="media-list">
  <% if post_data.empty? %>
      <p>検索条件に合うものがありません。</p>
  <% else %>
      <% post_data.each do |post| %>
          <% user = post['name'] %>
          <li class="media">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h1 class="panel-title"><%= user %></h1>
              </div>
              <div class="panel-body">
                <div class="media-left">
                  <img class="media-object img-rounded" src="<%= post['imageUrl'] %>" alt="" height="50" width="50">
                </div>
                <div class="media-body">
                  <div>
                    <p><%= link_to 'typetalkで見る', "https://typetalk.in/topics/#{post['topic_id']}/posts/#{post['post_id']}", :target => ["_blank"] %></p>
                    <span class="text-muted">投稿時間 <%= post['created_at'] %></span>
                  </div>
                  <div>
                    <%= simple_format(post['message']) %>
                  </div>
                  <div>
                    <p class="col-xs-3 bg-danger">️イイネの数❤︎️ <%= post['like'] %></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
      <% end %>
  <% end %>
</ul>

app/views/topics/_term_find_form.html.erb
<%= form_for form, :url => {:action => action} do |f| %>
    <p>
      <%= f.label :post_from, '表示期間:' %><br>
      <%= f.datetime_select :post_from, :use_month_numbers => true, :default => Time.now().beginning_of_month %> 〜<br>
      <%= f.datetime_select :post_to, :use_month_numbers => true, :default => Time.now().end_of_month %>
    </p>
    <p>
      <%= f.submit '検索する' %>
    </p>
<% end %>

app/views/topics/all.html.erb
<div class="row">
  <aside class="col-md-12 col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @topic_name %></h3>
      </div>
    </div>
    <%= render 'term_find_form', form: @form, action: "all_process" %>
  </aside>
  <div class="col-md-8 col-xs-12">

    <%= render 'post_list', post_data: @post_data %>

    <%= paginate @posts %>
  </div>
</div>

app/views/topics/all_post.js.erb
var post_data = '<% @post_data.each do |post| %>' +
    '<% user = post['name'] %>' +
    '<li class="media">' +
    '<div class="media-left">' +
    '<img class="media-object img-rounded" src="<%= post['imageUrl'] %>" alt="" height="50" width="50">' +
    '</div>' +
    '<div class="media-body">' +
    '<div>' +
    '<p><%= link_to 'typetalkで見る', "https://typetalk.in/topics/#{post['topic_id']}/posts/#{post['post_id']}", :target => ["_blank"] %></p>' +
    '<%= user %>' +
    '<span class="text-muted">posted at <%= post['created_at'] %></span>' +
    '</div>' +
    '<div>' +
    '<%= simple_format(post['message']) %>' +
    '</div>' +
    '<div>' +
    '<p class="col-xs-2 bg-danger">イイネの数 <%= post['like'] %></p>' +
    '</div>' +
    '</div>' +
    '</li>' +
    '<% end %>';

$("#ajax_list").html(post_data);
$("#time").html("<%= @time %>");

app/views/topics/follow.js.erb
var follow = '<%= link_to 'フォロー中', topics_unfollow_path(:id => @topic.topicId), class: 'btn btn-sm btn-primary active', method: :post, remote: true %>'
$("#follow_<%= @topic.topicId %>").html(follow);

app/views/topics/index.html.erb
<div class="row">
  <aside class="col-md-12 col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
    </div>
    <ul class="media-list">
      <li class="media">
        <div class="media-body">
          <p><%= link_to 'すべてのトピックの集計', topic_all_path %></p>
        </div>
      </li>
      <li class="media">
        <div class="media-body">
          <p><%= link_to 'ユーザーごとの集計', topic_user_path %></p>
        </div>
      </li>
      <li class="media">
        <div class="media-body">
          <p>データベース使用状況</p>
          <p><%= @record_count %>/10000</p>
        </div>
      </li>
      <li class="media">
        <!--
        <div class="media-body">
          <p><%#= link_to 'すべてのトピックの情報を最新に更新する', update_latest_path, remote: true %></p>
          <p>この作業には時間がかかります</p>
        </div>
        -->
      </li>
    </ul>
  </aside>
  <div class="col-md-8 col-xs-12">
    <ul class="media-list">
      <% @topics.each do |topic| %>
          <li class="media">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h1 class="panel-title"><%= topic['name'] %></h1>
              </div>
              <div class="panel-body">
                <div class="media-body">
                  <div>
                    <p>
                      <%= link_to '詳細', topic_path(:id => topic['id']), class: 'btn btn-sm btn-primary' %>
                      <%= link_to 'typetalkで見る', "https://typetalk.in/topics/#{topic['id']}", :target => ["_blank"], class: 'btn btn-sm btn-primary' %>
                      <span id="follow_<%= topic['id'] %>">
                      <% if topic['register'] == '1' %>
                      <%= link_to 'フォロー中', topics_unfollow_path(:id => topic['id']), class: 'btn btn-sm btn-primary active', method: :post, remote: true %>
                      <% else %>
                      <%= link_to 'フォローする', topics_follow_path(:id => topic['id']), class: 'btn btn-sm btn-default', method: :post, remote: true %>
                      <% end %>
                      </span>
                    </p>
                    <p>最終データ取得日：<%= topic['updated_at'] %></p>
                    <% unless topic['from'].nil? and topic['to'].nil? %>
                    <p id="from_to">投稿保存期間：<%= topic['from'].in_time_zone %> ～ <%= topic['to'].in_time_zone %></p>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/topics/new.html.erb
<div class="text-center">
  <h1>トピック 登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@topic) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :topicId, 'いいねの数を計測したいトピックのURL' %>
        <%= f.text_field :topicId, class: 'form-control' %>
      </div>
      
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/topics/past_post.js.erb
$('#flash_ajax').html(
    "<%= escape_javascript(render 'layouts/flash_messages') %>"
);

app/views/topics/show.html.erb
<div class="row">
  <aside class="col-md-12 col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @topic_name %></h3>
      </div>
    </div>
    <%= render 'term_find_form', form: @form, action: "show_process" %>
  </aside>
  <div class="col-md-8 col-xs-12">

    <%= render 'post_list', post_data: @post_data %>

    <%= paginate @posts %>
  </div>
</div>

app/views/topics/unfollow.js.erb
var unfollow = '<%= link_to 'フォローする', topics_follow_path(:id => @topic.topicId), class: 'btn btn-sm btn-default', method: :post, remote: true %>'
$("#follow_<%= @topic.topicId %>").html(unfollow);
$("#from_to").html('');

app/views/topics/update_latest.js.erb
$('#flash_ajax').html(
    "<%= escape_javascript(render 'layouts/flash_messages') %>"
);

app/views/topics/user.html.erb
<div class="row">
  <aside class="col-md-12 col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @topic_name %></h3>
      </div>
    </div>
    <%= render 'term_find_form', form: @form, action: "user_process" %>
  </aside>
  <div class="col-md-8 col-xs-12">
    <ul class="media-list">
      <% @post_data.each do |post| %>
          <li class="media">
            <div class="media-left">
              <img class="media-object img-rounded" src="<%= post['imageUrl'] %>" alt="" height="50" width="50">
            </div>
            <div class="media-body">
              <div>
                <%= post['fullName'] %>
              </div>
              <div>
                <p class='col-xs-3 bg-danger'>イイネの数❤　<%= post['like'] %></p>
              </div>
            </div>
          </li>
      <% end %>
    </ul>

    <%= paginate @page_posts %>
    
  </div>
</div>